services:
  app:
    build:
      context: ./
      dockerfile: ./ws-app/Dockerfile
    working_dir: /path
    stdin_open: true
    tty: true
    command: python3 app.py
    ports:
      - "8001:8001"
    volumes:
      - type: bind
        source: .
        target: /path
