name: docker

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - 
        name: Checkout
        uses: actions/checkout@v4

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/nirvn/ws

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ws-app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
